apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{.Values.deployment.labels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.labels.app}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{.Values.deployment.probes.liveness.path}}
              port: {{ .Values.deployment.port }}
          readinessProbe:
            httpGet:
              path: /{{.Values.deployment.probes.readiness.path}}
              port: {{ .Values.deployment.port }}
          env:
            - name: NODE_ENV
              value: {{.Values.deployment.env.NODE_ENV}}   
            - name: DATABASE_URL
              value: {{.Values.deployment.env.DATABASE_URL | quote}} 
            - name: DB_USER 
              value: {{.Values.deployment.env.DB_USER}}
            - name: DATABASE_PASSWORD
              value: {{.Values.deployment.env.DATABASE_PASSWORD}}
            - name: DB_HOST 
              value: {{.Values.deployment.env.DB_HOST}}
            - name: DB_PORT
              value: {{.Values.deployment.env.DB_PORT | quote}}
            - name: DB_DATABASE
              value: {{.Values.deployment.env.DB_DATABASE}}        
